server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
    org.apache.tomcat: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.hibernate:SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    logging:
      level:
        root=DEBUG:


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewn
    username: postgres
    password: postgres

  sql:
    init:
      mode: always

stats-server:
  url: http://stats-server:9090