server:
  port: 8080

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewn
    username: postgres
    password: postgres

  sql:
    init:
      mode: always